### PR TITLE
I have changed the overview page and added details about coronavirus, its symtoms precaution and more

### PR DESCRIPTION
**Pull request by Tejas1510**

### CODE REVIEW

**Comment by Tejas1510** [comment]
screencapture-127-0-0-1-5500-index-html-2020-10-01-10_42_12
This is the front page 
Hope you like it and merge the PR.
Thank you Sir

**Review by AnkitSharmaOnGithub — CHANGES_REQUESTED** [review]
Nice.

But I have few suggestions. Kindly improve these.

1) The topmost image has Mygov logo. We can use some other images. We can find them for free.

2)Also, Kindly remove the footer images that contains link to Mygov. Or we can change the heading to something like "Get connected to MyGov".

3) Also, header on all pages except index has extra spacing. Refer to :- https://nimb.ws/f4vEgk. 

Kindly fix these issues. 

### Thank you for contributing to this repo and most importantly Open Source. You have created a great design. Don't get demotivated by these suggestions. I have only done these tom improve the design. Thank you.

**Comment by Tejas1510** [comment]
Will surely work on this issue and make a PR soon

**Comment by AnkitSharmaOnGithub** [comment]
> Will surely work on this issue and make a PR soon

@Tejas1510 Thank you.

**Pull request closed without merging**
