### PR TITLE
Edited UI of Homepage 

### PR DESCRIPTION
**Pull request by Roshanpaswan**

### CODE REVIEW

**Comment by AnkitSharmaOnGithub** [comment]
Hello @Roshanpaswan . Your PR is in conflict with the current state. Kindly fix that. Thank you for the efforts. Really appreciated.

**Comment by Roshanpaswan** [comment]
I have fixed the conflict please check it out. Thank You

**Comment by AnkitSharmaOnGithub** [comment]
Hello @Roshanpaswan. Apologies for taking late action on your PR. The homepage design for your PR has some issues. Refer to https://nimb.ws/Pn6kTQ. Kindly create a new branch. Improve it and them create a new PR. 

For reference and inspiration, you could check https://github.com/arhaanb/covid19/tree/better-ui by @arhaanb which has a pretty good design. You could also work on the same design and add some image to it.

**Comment by Roshanpaswan** [comment]
please check i have open a new pull request with new design. I hope you like it. Thankyou 
Made an new UI for homepage #21

**Pull request closed without merging**
