### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by arhaanb**
Hi, I changed the UI on the Overview and the Countries pages. I went with a design that's much cleaner than before. I created new files for the new styles so that it doesn't disrupt the rest of the website. The rest of the pages can be changed by importing these stylesheets to them and changing the navbar html. Tell me what you think.

Thank you :)

#2 @AnkitSharmaOnGithub

### CODE REVIEW

**Comment by AnkitSharmaOnGithub** [comment]
@arhaanb  Nice.

But I have few suggestions. Kindly improve these.

The Data Visualizations page has broken. Refer to :- https://nimb.ws/0K7XkL

Also, header on some pages are different.
Kindly improve these.

Thank you for contributing to this repo and most importantly Open Source. You have created a great design.

**Comment by arhaanb** [comment]
image

The page looks fine on my server. I'll fix the headers.

**Comment by arhaanb** [comment]
image

The page looks fine to me. I'll fix the headers on all pages.

**Comment by arhaanb** [comment]
Check the latest commit. I've fixed the design in all pages, should look good now. Thank you for letting me help :)

**Comment by AnkitSharmaOnGithub** [comment]
Hello. Apologies for taking late action on your PR. The design looks pretty good. I have some feedbacks though.

1) Kindly add image to the pages to make them more attractive.
2) Kindly make the select bar on Country wise page look more appealing.

Once, these changes are done. Kindly make a PR. I would merge it ASAP.

**Comment by arhaanb** [comment]
@AnkitSharmaOnGithub Tell me which images you would like, I'll arrange them and design the page. Also I saw you assign someone else the same issue, so please make sure no repeated work takes place.

**Comment by AnkitSharmaOnGithub** [comment]
> @AnkitSharmaOnGithub Tell me which images you would like, I'll arrange them and design the page. Also I saw you assign someone else the same issue, so please make sure no repeated work takes place.

Hello @arhaanb. Apologies for late replying. I was unavailable for past few days.
No one else is working on these changes.
If you are still interested in the project. You can add Covid Related images like :- Precautions, What to do etc. So, as to make the page appealing.(If not, Thank you for all the work till date.)

**Pull request closed without merging**
